export const ROUTES = {
    MAIN: "/",
    SERVICES: "/services",
    BOOKING: "/booking",
    SERVICE: "/service",
    MASTER: "/master-info",
    TIMESBOOKING: "/times-booking",
    ORDER: "/order",
    MASTERFILTER: "/master-filter",
    RECORD: "/record",
    PROFILE: "/profile",
    CALENDAR: "/calendar",
    BONUS: "/bonus",
    FEEDBACK: "/feedback",
    CHOOSEPAGE: "/choose-page",
    SETTING: "/setting",
};
